-- calculator [Number 3, Number 2, Add, Number 4, Multiply] -- => 20.0
-- calculator [Number 2]                                    -- => 2.0
-- calculator [Number 3, Number 3, Multiply, SquareRoot]    -- => 3.0
-- calculator [Number 3, Number 2, Number 4, Add, Multiply] -- => 18.0